- name: demo on task level variables
  hosts: all
  tasks:
    - name: print domine
      ansible.builtin.debug:
        msg: helo from {{ domine }}
      vars:
        domine: mdevops333.online






