- name: demo on play level variables
  hosts: all
  tasks:
    vars:
      dns: mdevops333.online
      domine: front.mdevops333.online
  - name: print dns
    ansible.builtin.debug:
      msg: my dns is {{ dns}}
  - name: print dns
    ansible.builtin.debug:
     msg: my dns is {{ domine }}



