- name: aws parameter
  hosts: localhost
  connection: local
  tasks:
    - name: print parameter
      ansible.builtin.debug:
        msg: parameter - "{{ lookup('aws_ssm', 'dev.test', region='us-east-1' ) }}"