- name: Demo on Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo task for loop
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - banana

    - name: Demo task for loop
      ansible.builtin.debug:
        msg: City Name - {{ City.name }}, Quantity - {{ City.Capital }}
      loop:
        - {name: hyd, Capital: 10}
        - {name: Goa, Capital: 20}