- name: Demo on Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo task for loop
      ansible.builtin.debug:
        msg: Fruit Name - {{ cityname }}
      loop:
        - hyd
        - bnglor